/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#64568b',
        'on-primary': '#ffffff',
        'primary-container': '#9d8ec7',
        'on-primary-container': '#332658',
        secondary: '#65529c',
        'on-secondary': '#ffffff',
        'secondary-container': '#c1adfe',
        'on-secondary-container': '#4f3d85',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f4fafd',
        'on-surface': '#161d1f',
        'on-surface-variant': '#49454f',
        background: '#f4fafd',
        'on-background': '#161d1f',
        outline: '#7a757f',
        'outline-variant': '#cac4d0',
        'surface-container': '#e8eff1',
        'surface-container-low': '#eef5f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e2e9ec',
        'surface-variant': '#dde4e6',
        'inverse-surface': '#2b3234',
        'primary-fixed': '#e8ddff',
        'primary-fixed-dim': '#cebefa',
        tertiary: '#685f18',
        'tertiary-container': '#b8ad5e',
        'on-tertiary': '#ffffff',
      },
      fontSize: {
        'display': ['48px', { lineHeight: '56px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'max-width': '1400px',
      },
      maxWidth: {
        'content': '1400px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
